# Generated by Django 4.1.7 on 2023-02-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100)),
                ('is_available', models.JSONField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'priceHistory',
                'managed': False,
            },
        ),
    ]
