# Generated by Django 4.1.7 on 2023-02-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staking_status_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'managed': True},
        ),
    ]
